site_name: fresa 🍓
site_url: https://josekoalas.github.io/fresa
site_author: José Pazos Pérez

repo_url: https://github.com/josekoalas/fresa
repo_name: josekoalas/fresa
edit_uri: ""

theme:
  name: material
  features:
    - navigation.instant
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/lightbulb
        name: switch to dark mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

extra:
  version:
    provider: mike

nav:
  - home: index.md
  - engine design:
    - design: engine_design/design.md
    - features: engine_design/features.md
    - style: engine_design/style.md