site_name: fresa 🍓
site_url: https://josekoalas.github.io/fresa
site_author: José Pazos Pérez

repo_url: https://github.com/josekoalas/fresa
repo_name: josekoalas/fresa
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/lightbulb
        name: switch to dark mode

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

extra:
  version:
    provider: mike

nav:
  - getting started:
    - building the project: getting_started/building.md
    - a simple program: getting_started/first_project.md

  - reference:
    - engine: reference/engine.md
    - time: reference/time.md
    - math: reference/math.md

    - custom types:
      - type names: reference/types/type_names.md
      - constexpr for: reference/types/constexpr_for.md
      - atomic queue: reference/types/atomic_queue.md
      - strings: reference/types/strings.md

    - system manager: reference/system.md
    - job system: reference/jobs.md
    
    - tools:
      - logging: reference/tools/log.md
      - unit tests: reference/tools/unit_test.md